apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-app
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
      - name: backend
        image: backend-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      - name: frontend
        image: frontend-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
