apiVersion: v1
kind: Service
metadata:
  name: fullstack-service
spec:
  type: NodePort
  selector:
    app: fullstack-app
  ports:
    - name: backend
      port: 80
      targetPort: 5000
      nodePort: 30017
    - name: frontend
      port: 81
      targetPort: 3000
      nodePort: 30018
