name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        eval $(minikube docker-env)

    - name: Build Docker image
      run: |
        docker build -t <your-dockerhub-username>/hospital-frontend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.hideandseek }}" | docker login -u "${{ secrets.engsameertariq }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push <your-dockerhub-username>/hospital-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
